#!/bin/sh

# Fix graphical boot (bnc #615125)
if test -e /boot/grub/menu.lst && touch 2>/dev/null /boot/grub/canwrite ; then
    grep -q gfxmenu /boot/grub/menu.lst || sed -i -e '1igfxmenu (hd0,1)/boot/message' /boot/grub/menu.lst
fi
rm -f /boot/grub/canwrite

exit 0

# delete itself, as we only need this to run on first boot
rm -f /etc/init.d/firstboot

