#!/bin/sh

# HACK HACK HACK
cp /etc/menu.lst /boot/grub/
/usr/sbin/grub-set-default 0

# delete itself, as we only need this to run on first boot
rm -f /etc/init.d/suse_studio_custom

# Now sync, remount, and reboot!
sync
mount -oremount,ro /
sync
sleep 2
/sbin/reboot -f
